### ISSUE TITLE
Feature Request: Tenor Guitar

### ISSUE THREAD

**Issue by jgarte** [newlandsvalley/chord-builder#1]
Hi, how hard would it be to add tenor guitar?

It's tuned in 5ths: `C G D A`

https://en.wikipedia.org/wiki/Tenor_guitar

https://www.youtube.com/watch?v=aTjm60tm2WY

**Comment by newlandsvalley** [comment]
It should be straightforward.  I started this with just guitar and then added bass and piano later as and when Sturla requested them and just used the same approach for all of them.  It's probably best to take ```guitar``` as the starting point and create a ```tenor-guitar``` from it, amending it accordingly.

Lovely youtube example.  I see that there are various sites that have example chord voicings - for example https://eastwoodguitars.co.uk/blogs/news/tenor-guitar-chords-guide.

I could look at this later on if I get some time or I would accept a PR.

**Comment by jgarte** [comment]
Here's another tenor guitar gem:

Tiny Grimes, Art Tatum, and Slam Stewart:

https://www.youtube.com/watch?v=Nnur0jLOoAc

>  It's probably best to take guitar as the starting point and create a tenor-guitar from it, amending it accordingly.

I ended up using the `guitar` as a template.

**Comment by newlandsvalley** [comment]
I think this is sensible. If it's OK with you I'd prefer to review the PR when tenor guitar is complete and once that's merged, move on to uke.

Many thanks for the interest!

**Comment by jgarte** [comment]
> I think this is sensible. If it's OK with you I'd prefer to review the PR when tenor guitar is complete and once that's merged, move on to uke.

Of course, thank you for allowing me to collaborate with you on your project and for reviewing my code. I'm a PureScript newbie but I'm looking to learn more about the language as I go so any advice is much appreciated for my PS learning journey.

**Comment by newlandsvalley** [comment]
It would be a pleasure - if I can help at all, I will.  I hope my coding style is not too idiosyncratic.

**Comment by newlandsvalley** [comment]
Very many thanks, @jgarte for adding tenor guitar.
