### ISSUE TITLE
Feature Request: Enable GitHub Discussions

### ISSUE THREAD

**Issue by jgarte** [newlandsvalley/chord-builder#16]
Hi,

[GitHub Discussions](https://docs.github.com/en/discussions) can facilitate a way for the community and/or prospective [chord-editor](https://github.com/newlandsvalley/chord-editor) contributors to discuss directions for the project without opening an issue that is really a discussion topic.

Can you enable this feature?

See the guide here for doing that:

https://docs.github.com/en/discussions

**Comment by newlandsvalley** [comment]
I've taken a brief look.  As far as I can see, I'd first have to turn myself into an _organisation,_ which is hardly appropriate.

**Comment by jgarte** [comment]
Oh, didn't realize that that was a requirement. Feel free to close this issue in that case.
