### ISSUE TITLE
Piano Chord Title

### ISSUE THREAD

**Issue by Beaks857** [newlandsvalley/chord-builder#17]
Fantastic app which is just what I was looking for (a piano choard equivalent to the chordpic app). However, for the piano chord image, the text for the name of the chord is a little small when it is resized for adding to a song sheet. If the name text could be made the same size as used for the piano chords used by many of the Ultimate Guitar songsheets that would be brilliant: https://tabs.ultimate-guitar.com/tab/steely-dan/do-it-again-chords-3035016

**Comment by newlandsvalley** [comment]
Many thanks for your nice comments, @Beaks857. I think I see what you mean - when the image is resized to the smallest possible extent, then the title is too small to be read comfortably. One constraint that I have is that the scaling operation scales the title and piano together - meaning that the title size is always proportional to the piano size.  I don't want the title to look grotesquely large at larger scales.  Perhaps I might investigate what it looks like if I made the title about 50% bigger than it currently is.  What do you think?

**Comment by Beaks857** [comment]
Hi John,

 

It was very kind of you to respond to my comment.

 

Yes I think 50% larger would be fine.  I mean, it's not really bad at the moment, just a little small.

 

Brilliant app by the way and so simple to use.  I use the online Chordpic app (chordpic.com) for my guitar chords and it works in a similar fashion to your app :))

 

Kind regards,

 

Peter

 

Peter Coady

Email:   ***@***.***> ***@***.*** (for all replies)

**Comment by newlandsvalley** [comment]
I've increased the piano title size by about 70% - I think it looks OK now if you'd like to test it.

**Comment by Beaks857** [comment]
Hi John,

 

Many thanks.  I have added it to a page I am using as Cm7 70.  Comparing it with the same Cm7 chord below it, the title doesn't seem to be any larger.  I also superimposed the two chord diagrams on top of each other to confirm it and the titles seem to be the same size.  These chord diagrams are the size I am using at the moment and, at this size, they both seem very clear.  However, some songs would need them to be a bit smaller if the lyrics extend into the page further (I usually put the chord diagrams down the right hand side of the page close to the lyrics they refer to).

 

I hope this helps.

 

Kind regards,

 

Peter

 

Peter Coady

Email:   ***@***.***> ***@***.*** (for all replies)

**Comment by newlandsvalley** [comment]
Oh - I stupidly assumed you were a developer and would re-build and test the app yourself, but presumably you've just been using the 'try it here' link.  If so, I've now installed this version on the server I use and so the link should point to this latest version.  You may possibly have to refresh your browser cache to see the changes - usually control-shift-R.

**Comment by Beaks857** [comment]
Hi John,

 

Sorry for the slow response.  The new version is perfect.  Thank you so much for the update

 

Kind regards,

 

Peter

 

Peter Coady

Email:   ***@***.***> ***@***.*** (for all replies)

**Comment by newlandsvalley** [comment]
It's been a pleasure, Peter.  Many thanks for pointing it out.  I'll close the issue.

**Comment by Beaks857** [comment]
Thanks John.

 

Kind regards,

 

Peter

 

Peter Coady

Email:   ***@***.***> ***@***.*** (for all replies)
