### ISSUE TITLE
Refreshing the Tenor Guitar page errors

### ISSUE THREAD

**Issue by newlandsvalley** [newlandsvalley/chord-builder#8]
I think this is to do with translation to and fro between the URI string component and the ```FrettedInstrumentExample``` data type.  I think we need to decide on whether or not the URI component is ```tenorGuitar``` or ```tenorguitar```.  I suspect it will be a lot more straightforward to change it to the latter.

**Comment by jgarte** [comment]
Why do you think the latter will be more straightforward? Just curious

**Comment by newlandsvalley** [comment]
Just laziness - I'm guessing you can probably just use ```toLower``` when converting from the Example type.

**Comment by newlandsvalley** [comment]
Fixed by bd4d243f26b13b8f3397b16d428680cb116f060f
